name: build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: install packages build
        run: |
          sudo apt update
          sudo apt install -y devscripts equivs dput

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.CANONICAL_KEY }}
          passphrase: ${{ secrets.CANONICAL_PASSPHRASE }}

      - name: Build package
        run: |
          ubuntu/create-deb.sh ydotool hector.cao@canonical.com ppa:kivuteam/ppa
